red:
  join:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 151.0
    z: -3.5
    pitch: 0.0
    yaw: 0.0
  core:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 62.0
    z: -53.0
    pitch: 0.0
    yaw: 0.0
  spawn:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 53.0
    z: -40.5
    pitch: 0.0
    yaw: 0.0
blue:
  join:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 151.0
    z: 4.5
    pitch: 0.0
    yaw: 0.0
  core:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 62.0
    z: 53.0
    pitch: 0.0
    yaw: 0.0
  spawn:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 53.0
    z: 41.5
    pitch: 0.0
    yaw: 0.0
